/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.mpf.pkgfinal;

import java.awt.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Niko
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        super("Login Page");
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        ResetBtn = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        ExitImg = new javax.swing.JLabel();
        SignUpImg = new javax.swing.JLabel();
        SignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Title.setText("Login");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        username.setText("Username");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        password.setText("Password");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/playfull_icon.png"))); // NOI18N
        Logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Logo.setMaximumSize(new java.awt.Dimension(200, 100));
        Logo.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 130, 90));

        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 220, -1));

        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, -1));

        ResetBtn.setText("Reset");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        jPanel1.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("Exit");
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ExitImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/exit_icon.png"))); // NOI18N
        ExitImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitImgMouseClicked(evt);
            }
        });

        SignUpImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/signup_icon.png"))); // NOI18N
        SignUpImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpImgMouseClicked(evt);
            }
        });

        SignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp.setText("Sign Up");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignUpImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitImg)
                    .addComponent(SignUpImg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(SignUp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        String user = txtUser.getText();
        String pass = txtPass.getText();
        if(user.equals("")){
            
              
            JOptionPane.showMessageDialog(jPanel1,"Username must be filled","",JOptionPane.WARNING_MESSAGE);
        }else if(pass.equals("")){
            JOptionPane.showMessageDialog(jPanel1,"Password must be filled","",JOptionPane.WARNING_MESSAGE);
            }
        else if((user!=null) && (pass!=null)){
            JOptionPane.showMessageDialog(jPanel1,"Congratz u can pass");
            dispose();
            new MainPage().setVisible(true);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
         
        txtPass.setText(null);
        txtUser.setText(null);
        
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void ExitImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitImgMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_ExitImgMouseClicked

    private void SignUpImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpImgMouseClicked
        // TODO add your handling code here:
       //SignUpPage x = new SignUpPage();
       
       new SignUpPage().setVisible(true);
       
      // SignUpPage app = new SignUpPage();
    //        x.SignUpPage();
    
    addWindowListener(new SignUpPage.WindowEventHandler());
    }//GEN-LAST:event_SignUpImgMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //isi method display Sign Up Page
       
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
        
        
    }
    
    /*Exit = new javax.swing.JLabel;
    ExitImg = new javax.swing.JLabel;
    LoginBtn = new javax.swing.JButton;
    Logo = new javax.swing.JLabel;
    ResetBtn = new javax.swing.JButton;
    SignUp = new javax.swing.JLabel;
    SignUpImg = new javax.swing.JLabel;
    Title = new javax.swing.JLabel;
    password = new javax.swing.JLabel;
    username = new javax.swing.JLabel;
    
    jPanel1 = new javax.swing.JPanel;
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel ExitImg;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel SignUp;
    public static javax.swing.JLabel SignUpImg;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
