/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.mpf.pkgfinal;

import javax.swing.event.*;
import java.awt.*;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;
import javafx.scene.Scene;
import javafx.scene.media.MediaPlayer;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.imageio.ImageIO;


/**
 *
 * @author Niko
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        open = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        in = new javax.swing.JLabel();
        openIcon = new javax.swing.JLabel();
        help1 = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();
        inOutIcon = new javax.swing.JLabel();
        INOUT1 = new javax.swing.JLabel();
        PlayerPanel1 = new javax.swing.JPanel();
        bW = new javax.swing.JLabel();
        diskIcon = new javax.swing.JLabel();
        logo4 = new javax.swing.JLabel();
        Fw = new javax.swing.JLabel();
        PlayerPanel = new javax.swing.JLabel();
        Playlist = new javax.swing.JPanel();
        playlistPanelTxt = new javax.swing.JLabel();
        open1 = new javax.swing.JLabel();
        open2 = new javax.swing.JLabel();
        AddSongIF = new javax.swing.JInternalFrame();
        OSC = new javax.swing.JButton();
        OS = new javax.swing.JButton();
        txtSong = new javax.swing.JTextField();
        AddPlaylist = new javax.swing.JButton();
        IconCover = new javax.swing.JLabel();
        HelpIF = new javax.swing.JInternalFrame();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Main Page"); // NOI18N

        Menu.setBackground(new java.awt.Color(51, 255, 51));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/playfull_icon.png"))); // NOI18N

        open.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        open.setText("Open");

        help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        help.setText("Help");

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");

        in.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        in.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        in.setText("Menu Panel");

        openIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/open_icon.png"))); // NOI18N
        openIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openIconMouseExited(evt);
            }
        });

        help1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/help_icon.png"))); // NOI18N
        help1.setText("jLabel1");
        help1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                help1MouseClicked(evt);
            }
        });

        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/exit_icon.png"))); // NOI18N
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout1MousePressed(evt);
            }
        });

        inOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/expand_icon.png"))); // NOI18N
        inOutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inOutIconMouseClicked(evt);
            }
        });

        INOUT1.setText("IN/OUT");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(help1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(openIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(in, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addComponent(inOutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(INOUT1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openIcon))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(help)
                    .addComponent(help1))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout1)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(logout)))
                .addGap(56, 56, 56)
                .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inOutIcon))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(INOUT1)))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        PlayerPanel1.setBackground(new java.awt.Color(153, 153, 255));

        bW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/back_icon.png"))); // NOI18N

        diskIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        diskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/music_icon.png"))); // NOI18N
        diskIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diskIconMouseClicked(evt);
            }
        });

        logo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/play_icon.png"))); // NOI18N

        Fw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/forward_icon.png"))); // NOI18N

        PlayerPanel.setText("Player Panel");

        javax.swing.GroupLayout PlayerPanel1Layout = new javax.swing.GroupLayout(PlayerPanel1);
        PlayerPanel1.setLayout(PlayerPanel1Layout);
        PlayerPanel1Layout.setHorizontalGroup(
            PlayerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diskIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(bW)
                .addGap(18, 18, 18)
                .addComponent(logo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PlayerPanel)
                .addGap(58, 58, 58))
        );
        PlayerPanel1Layout.setVerticalGroup(
            PlayerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlayerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(diskIcon))
                    .addComponent(PlayerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlayerPanel1Layout.createSequentialGroup()
                        .addGroup(PlayerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bW, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Playlist.setBackground(new java.awt.Color(0, 102, 255));

        playlistPanelTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playlistPanelTxt.setForeground(new java.awt.Color(255, 255, 255));
        playlistPanelTxt.setText("Playlist Panel");

        open1.setForeground(new java.awt.Color(255, 255, 255));
        open1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/play_icon.png"))); // NOI18N
        open1.setText("Canon");

        open2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/delete_icon.png"))); // NOI18N

        AddSongIF.setClosable(true);
        AddSongIF.setIconifiable(true);
        AddSongIF.setMaximizable(true);
        AddSongIF.setResizable(true);
        AddSongIF.setTitle("Add New Song");
        AddSongIF.setToolTipText("");
        AddSongIF.setEnabled(false);
        AddSongIF.setVisible(true);

        OSC.setText("Open Song Cover");
        OSC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OSCMousePressed(evt);
            }
        });

        OS.setText("Open Song");
        OS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OSMousePressed(evt);
            }
        });

        txtSong.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AddPlaylist.setText("Add to Playlist");
        AddPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddPlaylistMousePressed(evt);
            }
        });

        IconCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mpf/pkgfinal/ImagesPackage/icons/music_icon.png"))); // NOI18N

        javax.swing.GroupLayout AddSongIFLayout = new javax.swing.GroupLayout(AddSongIF.getContentPane());
        AddSongIF.getContentPane().setLayout(AddSongIFLayout);
        AddSongIFLayout.setHorizontalGroup(
            AddSongIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddSongIFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddSongIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(IconCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OSC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSong))
                .addGap(30, 30, 30))
        );
        AddSongIFLayout.setVerticalGroup(
            AddSongIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSongIFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconCover, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OSC)
                .addGap(30, 30, 30)
                .addComponent(OS)
                .addGap(32, 32, 32)
                .addComponent(txtSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(AddPlaylist))
        );

        HelpIF.setClosable(true);
        HelpIF.setIconifiable(true);
        HelpIF.setMaximizable(true);
        HelpIF.setResizable(true);
        HelpIF.setTitle("Help Video");
        HelpIF.setEnabled(false);
        HelpIF.setVisible(true);
        HelpIF.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                HelpIFInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setText("VIdeo Error");

        javax.swing.GroupLayout HelpIFLayout = new javax.swing.GroupLayout(HelpIF.getContentPane());
        HelpIF.getContentPane().setLayout(HelpIFLayout);
        HelpIFLayout.setHorizontalGroup(
            HelpIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HelpIFLayout.setVerticalGroup(
            HelpIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PlaylistLayout = new javax.swing.GroupLayout(Playlist);
        Playlist.setLayout(PlaylistLayout);
        PlaylistLayout.setHorizontalGroup(
            PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlaylistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(open2)
                .addGap(27, 27, 27))
            .addGroup(PlaylistLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddSongIF)
                    .addGroup(PlaylistLayout.createSequentialGroup()
                        .addComponent(open1)
                        .addGap(49, 49, 49)
                        .addComponent(playlistPanelTxt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(HelpIF))
                .addContainerGap())
        );
        PlaylistLayout.setVerticalGroup(
            PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlaylistLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(open1)
                    .addComponent(playlistPanelTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddSongIF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HelpIF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(open2)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PlayerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PlayerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openIconMouseClicked
        /*File desktop1 = new File("/Desktop");
        Desktop desktop = Desktop.getDesktop();
        desktop.open());*/ 
       
      // AddSongClass();
       
//        AddSongIF.setVisible(true);
//        AddSongIF.setLocation(100);
//        
//      
//        Playlist.add(addSongInternal);
//        //Playlist.setLocation(/*CENTER_ALIGNMENT*/p);
//        
//        JLabel label = new JLabel(addSongInternal.getTitle(), JLabel.CENTER);
//    addSongInternal.add(label, BorderLayout.CENTER);
//
//    Playlist.setVisible(true);
//    
    }//GEN-LAST:event_openIconMouseClicked

    private void diskIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diskIconMouseClicked
    //Desktop.getDesktop().open(new File("video.mpg"));
    }//GEN-LAST:event_diskIconMouseClicked

    private void help1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help1MouseClicked
        JDesktopPane dp2 = new JDesktopPane();
        JInternalFrame HIF = new JInternalFrame("Help",true,true,true,true);
        dp2.add(HIF);
        HIF.setBounds(100, 100, 200, 500);
        
        JLabel label = new JLabel(HIF.getTitle(), JLabel.CENTER);
    HIF.add(label, BorderLayout.CENTER);

    HIF.setVisible(true);
    }//GEN-LAST:event_help1MouseClicked
//
    private void AddPlaylistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPlaylistMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlaylistMousePressed

    private void OSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OSMousePressed
 JFileChooser coverChooser = new JFileChooser();
        coverChooser.showOpenDialog(null);
        File C = coverChooser.getSelectedFile();
        String filename2= C.getName();
        ImageIcon icon2 = new ImageIcon(filename2);
        
        System.out.println(filename2);
        IconCover.setIcon(icon2);        // TODO add your handling code here:
    }//GEN-LAST:event_OSMousePressed

    private void OSCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OSCMousePressed
         JFileChooser coverChooser = new JFileChooser();
        coverChooser.showOpenDialog(null);
        File C = coverChooser.getSelectedFile();
        String filename2= C.getAbsolutePath();
        ImageIcon icon2 = new ImageIcon(filename2);
        
        
        IconCover.setIcon(icon2);
    }//GEN-LAST:event_OSCMousePressed

    private void HelpIFInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_HelpIFInternalFrameActivated
        
        //MediaPlayer  MP = new MediaPlayer("video.mpg");
        //MP.setAutoPlay(true);
    }//GEN-LAST:event_HelpIFInternalFrameActivated

    private void openIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openIconMouseExited
        AddSongIF.setVisible(false);
    }//GEN-LAST:event_openIconMouseExited

    private void logout1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MousePressed
       int result = JOptionPane.showConfirmDialog(Menu,
        "Are you sure you want to quit?",
        "Confirm Quit", JOptionPane.YES_NO_CANCEL_OPTION);
if (result == JOptionPane.YES_OPTION) {System.exit(0);}

//JOptionPane.showMessageDialog(Menu,"Apakah anda ingin keluar?");
           //JFrame.dispose();
    }//GEN-LAST:event_logout1MousePressed

    private void inOutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inOutIconMouseClicked
//        JFrame F = new JFrame();
//        F.add(new JPanel);
//        F.setSize(600,600);
//        F.setVisible(true);
//        F.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        
//        F.add(paintComponents(g));
//        
    }//GEN-LAST:event_inOutIconMouseClicked

//    public void paintComponent(Graphics g){AffineTransform at = AffineTransform.getTranslateInstance(160, 96);
//        at.scale(0.6,0.6);
//        BufferedImage a = LoadImage("back_icon.png");
//        
//        Graphics2D g2d = (Graphics2D) g;
//        
//        g2d.drawImage(a, at, OS);
//        }
//    
//    BufferedImage LoadImage(String filename){
//        BufferedImage img = null;
//        
//        try{
//            img = ImageIO.read(new File(filename));
//        }catch(IOException e){
//        
//        }return img;
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
               
            }
        });
        
        JFrame frame = new JFrame();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPlaylist;
    private javax.swing.JInternalFrame AddSongIF;
    private javax.swing.JLabel Fw;
    private javax.swing.JInternalFrame HelpIF;
    private javax.swing.JLabel INOUT1;
    private javax.swing.JLabel IconCover;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton OS;
    private javax.swing.JButton OSC;
    private javax.swing.JLabel PlayerPanel;
    private javax.swing.JPanel PlayerPanel1;
    private javax.swing.JPanel Playlist;
    private javax.swing.JLabel bW;
    private javax.swing.JLabel diskIcon;
    private javax.swing.JLabel help;
    private javax.swing.JLabel help1;
    private javax.swing.JLabel in;
    private javax.swing.JLabel inOutIcon;
    private java.awt.Label label1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo4;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel open;
    private javax.swing.JLabel open1;
    private javax.swing.JLabel open2;
    private javax.swing.JLabel openIcon;
    private javax.swing.JLabel playlistPanelTxt;
    private javax.swing.JTextField txtSong;
    // End of variables declaration//GEN-END:variables
}
